version: '3'

services:
  
  python:
    image:
    container_name:
    restart:
    ports:
    networks:
      - network

  mysql:
    image: etec-mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - network
      
  node:
    image:
    container_name:
    restart:
    ports:
    networks:
      - network

networks:
  network: